import { prop, getModelForClass, modelOptions } from "@typegoose/typegoose";
import { TimeStamps } from "@typegoose/typegoose/lib/defaultClasses";

/**
 * Persists a reference to each interview analysis job so the history
 * list can be displayed on the home screen.
 */
@modelOptions({
  schemaOptions: {
    collection: "tbl_interview_sessions",
    toObject: { virtuals: true },
    toJSON: { virtuals: true },
  },
})
export class InterviewSession extends TimeStamps {
  @prop({ required: true, index: true })
  ticketId!: string;

  /** Original file name provided at upload time */
  @prop({ required: false })
  fileName?: string;

  /** File size in bytes */
  @prop({ required: false })
  fileSizeBytes?: number;

  /** Last known job status from the microservice */
  @prop({ required: false, default: "queued" })
  status?: string;

  /** Computed overall score (0-100), stored after completion */
  @prop({ required: false })
  overallScore?: number | null;

  /** One-line summary generated by analysis */
  @prop({ required: false })
  summary?: string | null;

  /** Optional free-text label set by the user */
  @prop({ required: false })
  label?: string;
}

export const InterviewSessionModel = getModelForClass(InterviewSession);
